node {
   def mvnHome
   stage('Preparation') { 
      git 'https://github.com/BarathArivazhagan/jenkins-ci-cd-pipeline-workshop.git'
      mvnHome = tool 'M3'
   }
   stage('Build') {
      withEnv(["MVN_HOME=$mvnHome"]) {
         if (isUnix()) {
            dir("spring-boot-demo") {
              sh 'pwd'
              sh '"$MVN_HOME/bin/mvn" -Dmaven.test.failure.ignore clean install -DskipTests'
            
            }
         } 
      }
   }
   stage('Junit') {
        withEnv(["MVN_HOME=$mvnHome"]) {
            dir("spring-boot-demo") {
                    sh '"$MVN_HOME/bin/mvn" test'
            }
        }
   }
   stage('Docker Build') {
      dir("spring-boot-demo") {
              sh 'docker build -t barathece91/spring-boot-ci-demo:${BUILD_NUMBER}  .'
      }
   }
   stage('Docker Artifact Push') {
      dir("spring-boot-demo") {
        withCredentials([usernamePassword(credentialsId: 'docker-credentials', usernameVariable: 'USERNAME',passwordVariable: 'PASSWORD')]) {
         sh '''
         docker login -u $USERNAME -p $PASSWORD
         docker push barathece91/spring-boot-ci-demo:${BUILD_NUMBER}
         '''
        }
      }
   }
   stage('Deploy') {
      dir("spring-boot-demo") {
        sh '''
        echo stop the running containters
        CONTAINER_NAME='demo-app'
        echo contianer $CONTAINER_NAME
        CID=$(docker ps -q -f status=running -f name=^/${CONTAINER_NAME}$)
        if [ ! "${CID}" ]; then
          echo "Container doesn't exist"
        fi
        docker stop demo-app && docker rm demo-app
        echo existing containers are stopped
        docker run -d --name demo-app -p 8081:8080 barathece91/spring-boot-ci-demo:${BUILD_NUMBER}
        '''
      }
   }
  
   
}